//! Matrix operations over polynomial rings Z\[x]/(x^n+1).

use std::ops::{Add, Mul, Neg, Sub};

use num::{One, Zero};
use poly_ring_xnp1::{Polynomial, zq::ZqI64};

/// A matrix over polynomial rings Z[x]/(x^n+1), with fixed dimensions K1 x K2.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct Mat<T, const N: usize, const K1: usize, const K2: usize>
where
    T: Zero,
{
    pub(crate) polynomials: [[Polynomial<T, N>; K2]; K1],
}

impl<T, const N: usize, const K1: usize, const K2: usize> Mat<T, N, K1, K2>
where
    T: Zero,
{
    /// Create a matrix (K1 x K2) with polynomials generated by the given closure.
    pub(crate) fn from_fn<F>(mut f: F) -> Self
    where
        F: FnMut() -> Polynomial<T, N>,
    {
        Mat {
            polynomials: core::array::from_fn(|_| core::array::from_fn(|_| f())),
        }
    }

    /// Dot product of two matrices.
    ///
    /// ## Panics
    /// Panics if the number of columns of the first matrix is not equal to
    /// the number of rows of the second matrix.
    #[allow(clippy::needless_range_loop)]
    pub fn dot<const P: usize>(&self, other: &Mat<T, N, K2, P>) -> Mat<T, N, K1, P>
    where
        T: Clone + One,
        for<'a> &'a T: Add<Output = T> + Mul<Output = T> + Sub<Output = T>,
    {
        let mut polynomials =
            core::array::from_fn(|_| core::array::from_fn(|_| Polynomial::<T, N>::zero()));
        for i in 0..K1 {
            for j in 0..P {
                for k in 0..K2 {
                    polynomials[i][j] = polynomials[i][j].clone()
                        + self.polynomials[i][k].clone() * other.polynomials[k][j].clone();
                }
            }
        }
        Mat { polynomials }
    }

    /// Add two matrices.
    #[allow(clippy::needless_range_loop)]
    pub(crate) fn add(&self, other: &Mat<T, N, K1, K2>) -> Mat<T, N, K1, K2>
    where
        T: Clone + One,
        for<'a> &'a T: Add<Output = T> + Mul<Output = T> + Sub<Output = T>,
    {
        let mut polynomials =
            core::array::from_fn(|_| core::array::from_fn(|_| Polynomial::<T, N>::zero()));
        for i in 0..K1 {
            for j in 0..K2 {
                polynomials[i][j] =
                    self.polynomials[i][j].clone() + other.polynomials[i][j].clone();
            }
        }
        Mat { polynomials }
    }

    // Subtract two matrices.
    #[allow(clippy::needless_range_loop)]
    pub(crate) fn sub(&self, other: &Mat<T, N, K1, K2>) -> Mat<T, N, K1, K2>
    where
        T: Clone + One,
        for<'a> &'a T: Add<Output = T> + Mul<Output = T> + Neg<Output = T> + Sub<Output = T>,
    {
        let mut polynomials =
            core::array::from_fn(|_| core::array::from_fn(|_| Polynomial::<T, N>::zero()));
        for i in 0..K1 {
            for j in 0..K2 {
                polynomials[i][j] =
                    self.polynomials[i][j].clone() - other.polynomials[i][j].clone();
            }
        }
        Mat { polynomials }
    }

    pub(crate) fn flatten(&self) -> Vec<Polynomial<T, N>>
    where
        T: Clone,
    {
        self.polynomials
            .iter()
            .flat_map(|row| row.iter().cloned())
            .collect()
    }

    pub(crate) fn from_flatten(vec: Vec<Polynomial<T, N>>) -> Self
    where
        T: Clone + One,
        for<'a> &'a T: Add<Output = T> + Mul<Output = T> + Sub<Output = T>,
    {
        assert_eq!(vec.len(), K1 * K2);
        let mut polynomials =
            core::array::from_fn(|_| core::array::from_fn(|_| Polynomial::<T, N>::zero()));
        for i in 0..K1 {
            for j in 0..K2 {
                polynomials[i][j] = vec[i * K2 + j].clone();
            }
        }
        Mat { polynomials }
    }
}

// Implement From Vec<Vec> for Mat
impl<T, const N: usize, const K1: usize, const K2: usize> From<Vec<Vec<Polynomial<T, N>>>>
    for Mat<T, N, K1, K2>
where
    T: Zero + Clone + One,
    for<'a> &'a T: Add<Output = T> + Mul<Output = T> + Sub<Output = T>,
{
    fn from(vecs: Vec<Vec<Polynomial<T, N>>>) -> Self {
        assert_eq!(vecs.len(), K1);
        assert_eq!(vecs[0].len(), K2);
        let mut polynomials =
            core::array::from_fn(|_| core::array::from_fn(|_| Polynomial::<T, N>::zero()));
        for i in 0..K1 {
            for j in 0..K2 {
                polynomials[i][j] = vecs[i][j].clone();
            }
        }
        Mat { polynomials }
    }
}

impl<T, const N: usize, const K1: usize, const K2: usize> From<Mat<T, N, K1, K2>>
    for Vec<Vec<Polynomial<T, N>>>
where
    T: Zero + Clone + One,
    for<'a> &'a T: Add<Output = T> + Mul<Output = T> + Sub<Output = T>,
{
    fn from(mat: Mat<T, N, K1, K2>) -> Self {
        mat.polynomials
            .into_iter()
            .map(|row| row.to_vec())
            .collect::<Vec<_>>()
    }
}

/// Returns the identity matrix of size `size` x `size`, where each entry is a polynomial.
pub fn matrix_identity<const Q: i64, const N: usize>(
    size: usize,
) -> Vec<Vec<Polynomial<ZqI64<Q>, N>>> {
    let mut matrix = Vec::with_capacity(size);
    for i in 0..size {
        let mut row = Vec::with_capacity(size);
        for j in 0..size {
            if i == j {
                row.push(Polynomial::<ZqI64<Q>, N>::one());
            } else {
                row.push(Polynomial::<ZqI64<Q>, N>::zero());
            }
        }
        matrix.push(row);
    }
    matrix
}

/// Multiplies two matrices of polynomials.
/// The number of columns of the first matrix must be equal to the number of rows of the second matrix.
pub fn matrix_multiply<const Q: i64, const N: usize>(
    a: &[Vec<Polynomial<ZqI64<Q>, N>>],
    b: &[Vec<Polynomial<ZqI64<Q>, N>>],
) -> Vec<Vec<Polynomial<ZqI64<Q>, N>>> {
    let n = a.len();
    let m = b[0].len();
    let p = a[0].len();
    assert_eq!(
        p,
        b.len(),
        "Number of columns of the first matrix must be equal to the number of rows of the second matrix"
    );

    let mut result = vec![vec![Polynomial::<ZqI64<Q>, N>::zero(); m]; n];
    for i in 0..n {
        for j in 0..m {
            for k in 0..p {
                result[i][j] = result[i][j].clone() + a[i][k].clone() * b[k][j].clone();
            }
        }
    }
    result
}

/// Creates a matrix of polynomials with the given number of rows and columns,
/// where each polynomial is generated by the provided closure.
pub fn matrix_from_fn<const Q: i64, const N: usize>(
    rows: usize,
    cols: usize,
    mut f: impl FnMut() -> Polynomial<ZqI64<Q>, N>,
) -> Vec<Vec<Polynomial<ZqI64<Q>, N>>> {
    let mut matrix = Vec::with_capacity(rows);
    for _ in 0..rows {
        let mut row = Vec::with_capacity(cols);
        for _ in 0..cols {
            row.push(f());
        }
        matrix.push(row);
    }
    matrix
}

/// Adds two matrices of polynomials element-wise.
/// The two matrices must have the same dimensions.
pub fn matrix_add<const Q: i64, const N: usize>(
    a: &[Vec<Polynomial<ZqI64<Q>, N>>],
    b: &[Vec<Polynomial<ZqI64<Q>, N>>],
) -> Vec<Vec<Polynomial<ZqI64<Q>, N>>> {
    let n = a.len();
    let m = a[0].len();
    assert_eq!(
        n,
        b.len(),
        "Two matrices must have the same number of rows for addition"
    );
    assert_eq!(
        m,
        b[0].len(),
        "Two matrices must have the same number of columns for addition"
    );
    let mut result = vec![vec![Polynomial::<ZqI64<Q>, N>::zero(); m]; n];
    for i in 0..n {
        for j in 0..m {
            result[i][j] = a[i][j].clone() + b[i][j].clone();
        }
    }
    result
}

/// Extends a matrix of polynomials by appending an identity matrix to the right.
pub fn matrix_extend_with<const Q: i64, const N: usize>(
    b: &[Vec<Polynomial<ZqI64<Q>, N>>],
    a: &mut [Vec<Polynomial<ZqI64<Q>, N>>],
) {
    let n = a.len();
    assert_eq!(
        n,
        b.len(),
        "Two matrices must have the same number of rows for extension"
    );
    for i in 0..n {
        a[i].extend_from_slice(&b[i]);
    }
}

pub fn matrix_change_modulus<const Q1: i64, const Q2: i64, const N: usize>(
    matrix: Vec<Vec<Polynomial<ZqI64<Q1>, N>>>,
) -> Vec<Vec<Polynomial<ZqI64<Q2>, N>>> {
    matrix
        .iter()
        .map(|row| {
            row.iter()
                .map(|p| p.mapv(|x| x.change_modulus()))
                .collect::<Vec<_>>()
        })
        .collect::<Vec<_>>()
}

impl<T, const N: usize, const K1: usize, const K2: usize> serde::Serialize for Mat<T, N, K1, K2>
where
    T: Zero + Clone + One + serde::Serialize,
    for<'a> &'a T: Add<Output = T> + Mul<Output = T> + Sub<Output = T>,
{
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        let vecs: Vec<Vec<Polynomial<T, N>>> =
            self.polynomials.iter().map(|row| row.to_vec()).collect();
        vecs.serialize(serializer)
    }
}

impl<'de, T, const N: usize, const K1: usize, const K2: usize> serde::Deserialize<'de>
    for Mat<T, N, K1, K2>
where
    T: Zero + Clone + One + serde::Deserialize<'de>,
    for<'a> &'a T: Add<Output = T> + Mul<Output = T> + Sub<Output = T>,
{
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let vecs: Vec<Vec<Polynomial<T, N>>> = Vec::deserialize(deserializer)?;
        Ok(Mat::from(vecs))
    }
}

#[cfg(test)]
mod tests {
    use poly_ring_xnp1::zqi64_vec;

    use super::*;

    const N: usize = 4;

    #[test]
    fn test_to_from_vecs() {
        let a_0_0 = Polynomial::<i32, N>::new(vec![1, 2, 3]);
        let a_0_1 = Polynomial::<i32, N>::new(vec![4, 5, 6]);
        let a_1_0 = Polynomial::<i32, N>::new(vec![7, 8, 9]);
        let a_1_1 = Polynomial::<i32, N>::new(vec![10, 11, 12]);

        let a = Mat::<i32, N, 2, 2> {
            polynomials: [
                [a_0_0.clone(), a_0_1.clone()],
                [a_1_0.clone(), a_1_1.clone()],
            ],
        };

        let vecs = Vec::from(a.clone());
        let b = Mat::from(vecs);

        assert_eq!(a.polynomials, b.polynomials);
    }

    #[test]
    fn test_from_fn() {
        let a = Mat::<i32, N, 2, 2>::from_fn(|| Polynomial::<i32, N>::new(vec![1, 2, 3]));

        let expected = vec![
            vec![Polynomial::<i32, N>::new(vec![1, 2, 3]); 2],
            vec![Polynomial::<i32, N>::new(vec![1, 2, 3]); 2],
        ];
        assert_eq!(Vec::from(a), expected);
    }

    #[test]
    fn test_dot() {
        let a_0_0 = Polynomial::<i32, N>::new(vec![1, 2, 3]);
        let a_0_1 = Polynomial::<i32, N>::new(vec![4, 5, 6]);

        // 1x2 matrix
        let a = Mat::<i32, N, 1, 2> {
            polynomials: [[a_0_0.clone(), a_0_1.clone()]],
        };

        let b_0_0 = Polynomial::<i32, N>::new(vec![1, 2]);
        let b_1_0 = Polynomial::<i32, N>::new(vec![3, 4]);

        // 2x1 matrix
        let b = Mat::<i32, N, 2, 1> {
            polynomials: [[b_0_0.clone()], [b_1_0.clone()]],
        };

        let c = a.dot(&b);

        let expected = [[a_0_0.clone() * b_0_0.clone() + a_0_1.clone() * b_1_0.clone()]];
        assert_eq!(c.polynomials, expected);
    }

    #[test]
    fn test_add() {
        let a_0_0 = Polynomial::<i32, N>::new(vec![1, 2, 3]);
        let a_0_1 = Polynomial::<i32, N>::new(vec![4, 5, 6]);

        // 1x2 matrix
        let a = Mat::<i32, N, 1, 2> {
            polynomials: [[a_0_0.clone(), a_0_1.clone()]],
        };

        let b_0_0 = Polynomial::<i32, N>::new(vec![1, 2, 3]);
        let b_0_1 = Polynomial::<i32, N>::new(vec![4, 5, 6]);

        // 1x2 matrix
        let b = Mat::<i32, N, 1, 2> {
            polynomials: [[b_0_0.clone(), b_0_1.clone()]],
        };

        let c = a.add(&b);

        let expected = [[a_0_0.clone() + b_0_0.clone(), a_0_1.clone() + b_0_1.clone()]];
        assert_eq!(c.polynomials, expected);
    }

    #[test]
    fn test_matrix_multiply() {
        const Q: i64 = 12289;
        const N: usize = 4;
        let a = vec![
            vec![
                Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![1, 2, 0, 0; Q]),
                Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![3, 4, 0, 0; Q]),
            ],
            vec![
                Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![5, 6, 0, 0; Q]),
                Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![7, 8, 0, 0; Q]),
            ],
        ];
        let b = vec![
            vec![Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![1, 0, 0, 0; Q])],
            vec![Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![0, 1, 0, 0; Q])],
        ];
        let c = matrix_multiply::<Q, N>(&a, &b);
        assert_eq!(c.len(), a.len());
        assert_eq!(c[0].len(), b[0].len());
        assert_eq!(
            c[0][0],
            Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![1, 2, 0, 0; Q])
                * Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![1, 0, 0, 0; Q])
                + Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![3, 4, 0, 0; Q])
                    * Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![0, 1, 0, 0; Q])
        );
        assert_eq!(
            c[1][0],
            Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![5, 6, 0, 0; Q])
                * Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![1, 0, 0, 0; Q])
                + Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![7, 8, 0, 0; Q])
                    * Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![0, 1, 0, 0; Q])
        );
    }

    #[test]
    fn test_matrix_from_fn() {
        const Q: i64 = 12289;
        const N: usize = 4;
        let matrix = matrix_from_fn::<Q, N>(2, 3, || {
            Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![1, 2, 3, 4; Q])
        });
        assert_eq!(matrix.len(), 2);
        assert_eq!(matrix[0].len(), 3);
        for row in matrix {
            for poly in row {
                assert_eq!(
                    poly,
                    Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![1, 2, 3, 4; Q])
                );
            }
        }
    }

    #[test]
    fn test_matrix_add() {
        const Q: i64 = 12289;
        const N: usize = 4;
        let a = vec![
            vec![
                Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![1, 2, 0, 0; Q]),
                Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![3, 4, 0, 0; Q]),
            ],
            vec![
                Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![5, 6, 0, 0; Q]),
                Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![7, 8, 0, 0; Q]),
            ],
        ];
        let b = vec![
            vec![
                Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![1, 1, 0, 0; Q]),
                Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![1, 1, 0, 0; Q]),
            ],
            vec![
                Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![1, 1, 0, 0; Q]),
                Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![1, 1, 0, 0; Q]),
            ],
        ];
        let c = matrix_add::<Q, N>(&a, &b);
        assert_eq!(c.len(), a.len());
        assert_eq!(c[0].len(), a[0].len());
        assert_eq!(
            c[0][0],
            Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![2, 3, 0, 0; Q])
        );
        assert_eq!(
            c[0][1],
            Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![4, 5, 0, 0; Q])
        );
        assert_eq!(
            c[1][0],
            Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![6, 7, 0, 0; Q])
        );
        assert_eq!(
            c[1][1],
            Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![8, 9, 0, 0; Q])
        );
    }

    #[test]
    fn test_matrix_extend_with() {
        const Q: i64 = 12289;
        const N: usize = 4;
        let mut a = vec![
            vec![
                Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![1, 2, 0, 0; Q]),
                Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![3, 4, 0, 0; Q]),
            ],
            vec![
                Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![5, 6, 0, 0; Q]),
                Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![7, 8, 0, 0; Q]),
            ],
        ];
        let b = vec![
            vec![
                Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![9, 10, 0, 0; Q]),
                Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![11, 12, 0, 0; Q]),
            ],
            vec![
                Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![13, 14, 0, 0; Q]),
                Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![15, 16, 0, 0; Q]),
            ],
        ];
        matrix_extend_with::<Q, N>(&b, &mut a);
        assert_eq!(a.len(), b.len());
        assert_eq!(a[0].len(), b[0].len() * 2);
        assert_eq!(
            a[0][2],
            Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![9, 10, 0, 0; Q])
        );
        assert_eq!(
            a[0][3],
            Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![11, 12, 0, 0; Q])
        );
        assert_eq!(
            a[1][2],
            Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![13, 14, 0, 0; Q])
        );
        assert_eq!(
            a[1][3],
            Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![15, 16, 0, 0; Q])
        );
    }

    #[test]
    fn test_flatten_and_flatten_back() {
        const Q: i64 = 12289;
        const N: usize = 4;
        let matrix = vec![
            vec![
                Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![1, 2, 0, 0; Q]),
                Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![3, 4, 0, 0; Q]),
            ],
            vec![
                Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![5, 6, 0, 0; Q]),
                Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![7, 8, 0, 0; Q]),
            ],
        ];
        let mat: Mat<ZqI64<Q>, N, 2, 2> = Mat::from(matrix.clone());
        let flattened = mat.flatten();

        let expected_flattened = vec![
            Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![1, 2, 0, 0; Q]),
            Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![3, 4, 0, 0; Q]),
            Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![5, 6, 0, 0; Q]),
            Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![7, 8, 0, 0; Q]),
        ];
        assert_eq!(flattened, expected_flattened);

        let mat_back = Mat::from_flatten(flattened);
        assert_eq!(mat.polynomials, mat_back.polynomials);
    }

    #[test]
    fn test_serialize_deserialize() {
        const Q: i64 = 12289;
        const N: usize = 4;
        let matrix = vec![
            vec![
                Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![1, 2, 0, 0; Q]),
                Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![3, 4, 0, 0; Q]),
            ],
            vec![
                Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![5, 6, 0, 0; Q]),
                Polynomial::<ZqI64<Q>, N>::new(zqi64_vec![7, 8, 0, 0; Q]),
            ],
        ];
        let mat: Mat<ZqI64<Q>, N, 2, 2> = Mat::from(matrix.clone());

        let serialized = serde_json::to_string(&mat).unwrap();
        let deserialized: Mat<ZqI64<Q>, N, 2, 2> = serde_json::from_str(&serialized).unwrap();

        assert_eq!(mat.polynomials, deserialized.polynomials);
    }
}
