//! Matrix operations over polynomial rings Z\[x]/(x^n+1).

use std::ops::{Add, Mul, Sub};

use num::{One, Zero};
use poly_ring_xnp1::Polynomial;

/// A matrix over polynomial rings Z[x]/(x^n+1), with fixed dimensions K1 x K2.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct Mat<T, const N: usize, const K1: usize, const K2: usize>
where
    T: Zero,
{
    pub(crate) polynomials: [[Polynomial<T, N>; K2]; K1],
}

impl<T, const N: usize, const K1: usize, const K2: usize> Mat<T, N, K1, K2>
where
    T: Zero,
{
    /// Create a matrix (K1 x K2) with polynomials generated by the given closure.
    pub(crate) fn from_fn<F>(mut f: F) -> Self
    where
        F: FnMut() -> Polynomial<T, N>,
    {
        Mat {
            polynomials: core::array::from_fn(|_| core::array::from_fn(|_| f())),
        }
    }

    /// Dot product of two matrices.
    ///
    /// ## Panics
    /// Panics if the number of columns of the first matrix is not equal to
    /// the number of rows of the second matrix.
    #[allow(clippy::needless_range_loop)]
    pub fn dot<const P: usize>(&self, other: &Mat<T, N, K2, P>) -> Mat<T, N, K1, P>
    where
        T: Clone + One,
        for<'a> &'a T: Add<Output = T> + Mul<Output = T> + Sub<Output = T>,
    {
        let mut polynomials =
            core::array::from_fn(|_| core::array::from_fn(|_| Polynomial::<T, N>::zero()));
        for i in 0..K1 {
            for j in 0..P {
                for k in 0..K2 {
                    polynomials[i][j] = polynomials[i][j].clone()
                        + self.polynomials[i][k].clone() * other.polynomials[k][j].clone();
                }
            }
        }
        Mat { polynomials }
    }

    /// Add two matrices.
    #[allow(clippy::needless_range_loop)]
    pub(crate) fn add(&self, other: &Mat<T, N, K1, K2>) -> Mat<T, N, K1, K2>
    where
        T: Clone + One,
        for<'a> &'a T: Add<Output = T> + Mul<Output = T> + Sub<Output = T>,
    {
        let mut polynomials =
            core::array::from_fn(|_| core::array::from_fn(|_| Polynomial::<T, N>::zero()));
        for i in 0..K1 {
            for j in 0..K2 {
                polynomials[i][j] =
                    self.polynomials[i][j].clone() + other.polynomials[i][j].clone();
            }
        }
        Mat { polynomials }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const N: usize = 4;

    #[test]
    fn test_dot() {
        let a_0_0 = Polynomial::<i32, N>::new(vec![1, 2, 3]);
        let a_0_1 = Polynomial::<i32, N>::new(vec![4, 5, 6]);

        // 1x2 matrix
        let a = Mat::<i32, N, 1, 2> {
            polynomials: [[a_0_0.clone(), a_0_1.clone()]],
        };

        let b_0_0 = Polynomial::<i32, N>::new(vec![1, 2]);
        let b_1_0 = Polynomial::<i32, N>::new(vec![3, 4]);

        // 2x1 matrix
        let b = Mat::<i32, N, 2, 1> {
            polynomials: [[b_0_0.clone()], [b_1_0.clone()]],
        };

        let c = a.dot(&b);

        let expected = [[a_0_0.clone() * b_0_0.clone() + a_0_1.clone() * b_1_0.clone()]];
        assert_eq!(c.polynomials, expected);
    }

    #[test]
    fn test_add() {
        let a_0_0 = Polynomial::<i32, N>::new(vec![1, 2, 3]);
        let a_0_1 = Polynomial::<i32, N>::new(vec![4, 5, 6]);

        // 1x2 matrix
        let a = Mat::<i32, N, 1, 2> {
            polynomials: [[a_0_0.clone(), a_0_1.clone()]],
        };

        let b_0_0 = Polynomial::<i32, N>::new(vec![1, 2, 3]);
        let b_0_1 = Polynomial::<i32, N>::new(vec![4, 5, 6]);

        // 1x2 matrix
        let b = Mat::<i32, N, 1, 2> {
            polynomials: [[b_0_0.clone(), b_0_1.clone()]],
        };

        let c = a.add(&b);

        let expected = [[a_0_0.clone() + b_0_0.clone(), a_0_1.clone() + b_0_1.clone()]];
        assert_eq!(c.polynomials, expected);
    }
}
